import {
  BarChart3,
  Bot,
  Calendar,
  CheckCircle2,
  Clock,
  CreditCard,
  DollarSign,
  Fan,
  Grid2X2,
  Handshake,
  Home,
  Link as LinkIcon,
  List,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MousePointerClick,
  Refrigerator,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Star,
  Zap,
  TrendingUp,
  UserPlus,
  Users,
  EyeOff,
  Wrench,
  Droplet,
} from "lucide-react";

export function iconFor(name: string) {
  const key = name.toLowerCase();

  const map: Record<string, React.ComponentType<{ className?: string }>> = {
    shield: ShieldCheck,
    lock: Lock,
    clock: Clock,
    sparkle: Sparkles,
    sparkles: Sparkles,
    grid: Grid2X2,
    zap: Zap,
    users: Users,
    star: Star,
    list: List,
    cursor: MousePointerClick,
    mail: Mail,
    login: UserPlus,
    "map-pin": MapPin,
    mappin: MapPin,
    milestone: CheckCircle2,
    "message-circle": MessageCircle,
    "credit-card": CreditCard,
    "check-circle": CheckCircle2,
    home: Home,
    "trending-up": TrendingUp,
    calculator: BarChart3,
    link: LinkIcon,
    "eye-off": EyeOff,
    handshake: Handshake,
    refresh: RefreshCw,
    "dollar-sign": DollarSign,
    "bar-chart": BarChart3,
    layout: Grid2X2,
    "user-plus": UserPlus,
    bot: Bot,
    calendar: Calendar,

    // service icons
    wrench: Wrench,
    droplet: Droplet,
    fan: Fan,
    refrigerator: Refrigerator,
  };

  return map[key] ?? Sparkles;
}
